# This file configures AppVeyor to run builds on Windows machines for each pull
# request, to ensure the tests pass and to build Windows wheels of pyAT. If the
# build is triggered by a tag and the tag name starts with "pyat" then the
# wheels are uploaded to TestPyPI using twine. For this repository
# TWINE_USERNAME and TWINE_PASSWORD are set in AppVeyor under
# Settings -> Environment -> Environment variables.
image: Visual Studio 2015
platform: x64
environment:
  # Build against the oldest supported version of numpy.
  CIBW_BEFORE_BUILD: "python -m pip install numpy==1.14.3"
  matrix:
   - PYTHON: 27
   - PYTHON: 35
   - PYTHON: 36
   - PYTHON: 37
   - PYTHON: 38

install:
  - set "PATH=C:\Python%PYTHON%-x64;C:\Python%PYTHON%-x64\Scripts;%PATH%"
  - python -m virtualenv venv
  - venv\Scripts\activate
  - cd pyat
  - pip install --only-binary=numpy,scipy -r requirements.txt

before_build:
  - python setup.py develop

build_script:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG_NAME -eq $null) {
        $env:APPVEYOR_REPO_TAG_NAME = "None"
      }
      if ($env:APPVEYOR_REPO_TAG_NAME.StartsWith("pyat") -And ($env:PYTHON -eq 37)) {
        rm "build" -r -fo
        python -m pip install --upgrade cibuildwheel
        & cmd /c 'cibuildwheel 2>&1' --output-dir wheelhouse
        if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode )  }
        python setup.py sdist --dist-dir=wheelhouse
        if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode )  }
        python -m pip install twine
        python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*
      }
      else {
        python -m pip install pytest-cov
        python -m pytest test --cov-report term-missing --cov=at
      }
