# This file configures Travis CI to run builds on Linux and Mac machines for
# each pull request, to ensure the tests pass and to build Linux and Mac wheels
# of pyAT. If the build is triggered by a tag and the tag name starts with
# "pyat" then the wheels are uploaded to TestPyPI using twine. For this
# repository TWINE_USERNAME and TWINE_PASSWORD are set in Travis CI under
# More options -> Settings -> Environment Variables.
dist: xenial
language: python
env:
  global:
    - CIBW_BEFORE_BUILD='pip install numpy'
matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: osx
      language: generic
      env: PYTHON=2
    - os: osx
      language: generic
      env: PYTHON=3

install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    python$PYTHON -m pip install virtualenv
    python$PYTHON -m virtualenv venv
    source venv/bin/activate
  else
    pip install virtualenv
    python -m virtualenv venv
    source venv/bin/activate
  fi
  cd pyat
  pip install --only-binary=numpy,scipy -r requirements.txt

before_script:
  - python setup.py develop

script: |
  PYTHON_VERSION=$(python -V 2>&1 | cut -d ' ' -f 2 | cut -d '.' -f 1,2)
  if [[ $TRAVIS_TAG == pyat* ]] && [[ $PYTHON_VERSION == 3.6 ]]; then
    rm -rf build
    python -m pip install --upgrade cibuildwheel
    cibuildwheel --output-dir wheelhouse
    python -m pip install twine
    python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  else
    python -m pip install pytest-cov
    python -m pytest test --cov-report term-missing --cov=at
  fi
