# theme: jekyll-theme-cayman
# theme: minima
# remote_theme: jekyll/minima
remote_theme: tomjoht/documentation-theme-jekyll

title: Accelerator Toolbox
# email: your-email@example.com
#description: >- # this means to ignore newlines until "baseurl:"
#  A toolbox for modelling particle accelerators in Matlab or python

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      topnav: topnav
  -
    scope:
      path: "m"
      type: "pages"
    values:
      sidebar: matlab_sidebar

header_pages:
  - matlab.md
  - python.md
  - about.md

plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-github-metadata
  - jekyll-relative-links

site_title: Accelerator Toolbox
topnav_title: Accelerator Toolbox
feedback_disable: true
company_name: atcollab

include:
  - _images
  - _static

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - doctrees
