# This workflow will install Python dependencies, run tests and lint with a
# variety of Python version
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Matlab tests

on:
  push:
  workflow_dispatch:
#  pull_request:
#
#defaults:
#  run:
#    working-directory: pyat

jobs:
  matlab_tests:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        release: R2022a

    - name: Atmexall
      uses: matlab-actions/run-command@v1
      with:
        command: run('atmat/atpath');savepath('pathdef.m');atmexall;pyenv('Version',fullfile(getenv('pythonLocation'),'bin','python'));

    - name: Build and install at
      run: python -m pip install -e "./pyat[dev]"

    - name: Run tests
      uses: matlab-actions/run-command@v1
      with:
        command: disp(table(assertSuccess(run(testsuite('atmat/attests',Tag='GitHub')))))
#
#    - name: Set up Matlab engine for python
#      run: python setup.py build --build-base=$(mktemp -d) install
#      working-directory: /usr/local/MATLAB/R2022a/extern/engines/python
#
#    - name: Test with pytest
#      run: python -m pytest pyat/test_matlab
